---
- name: install common packages
  tags:
  - base
  apt:
    pkg:
      - git
      - tmux
      - netcat-openbsd
      - gpg
      - curl
      - eject     # piece of mind for usb drives.
      - vim-nox   # replaces vim.basic/vim.tiny
      - emacs-nox
      - rsync
    state: present

- name: install hwraid keys.
  tags:
    - base
  when: base_disk_monitoring
  apt_key:
    url: "https://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key"
    state: present

- name: add hwraid.le-vert.net apt repository
  tags:
    - hwraid
  when: base_disk_monitoring
  apt_repository:
    repo: "deb [arch=amd64] http://hwraid.le-vert.net/debian buster main"
    state: present

- name: update package lists
  tags:
    - base
  apt:
    update_cache: true

- name: install additional disk monitoring packages
  tags:
    - base
  when: base_disk_monitoring
  apt: 
    pkg:
      - zfsutils-linux
      - hddtemp
      - smartmontools
      - megacli
    state: present

- name: install cpupower utils for freq-adjustments/info
  tags:
    - base
  when: base_cpupower
  apt:
    pkg:
      - linux-cpupower
    state: present

- name: install strongswan
  tags:
    - base
  when: base_strongswan
  apt:
    pkg:
      - strongswan
    state: present

- name: check tmux config exists
  tags:
    - base
  stat:
    path: "/home/chiefengineer/{{ item }}"
  register: config_file
  loop:
    - .tmux.conf
    - .vimrc

- name: install my configs
  tags:
    - base
  copy:
    src: "configs/{{ item.item }}"
    dest: "/home/chiefengineer/{{ item.item }}"
    owner: "chiefengineer"
    group: "chiefengineer"
    mode: 0644
  when: not item.stat.exists
  loop: "{{ config_file.results }}"

- name: bnx2 firmware drivers
  when: bnx2_install
  apt:
    pkg:
      - firmware-bnx2
    state: present

- name: basic non-free firmware drivers (tg3 nic)
  when: tg3_install
  apt:
    pkg:
      - firmware-misc-nonfree
    state: present

- name: install custom packages...
  when: base_custom_packages_install
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ base_custom_packages }}"

- name: upgrade all packages
  tags:
    - base
  when: base_dist_upgrade
  apt:
    upgrade: dist
