---
- name: install hwraid keys.
  tags:
    - base
  when: base_disk_monitoring
  apt_key:
    url: "https://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key"
    state: present

- name: add nginx apt repository
  tags:
    - nginx
  when: base_disk_monitoring
  apt_repository:
    repo: "deb [arch=amd64] http://hwraid.le-vert.net/debian buster main"
    state: present

- name: update package lists
  tags:
    - base
  apt:
    update_cache: true

- name: install common packages
  tags:
  - base:
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - tmux
    - emacs-nox
    - vimtiny
    - netcat-openbsd

- name: install additional disk monitoring packages
  tags:
    - base
  when: base_disk_monitoring
  apt: pkg={{ item }} state=present
  with_items:
    - zfsutils-linux
    - hddtemp
    - smartmontools
    - megacli

- name: upgrade all packages
  tags:
    - base
  when: base_dist_upgrade
  apt:
    upgrade: dist
