---
- name: install common packages
  tags:
  - base
  apt:
    pkg:
      - git
      - tmux
      - emacs-nox
      - vim-tiny
      - netcat-openbsd
      - gpg
      - curl
      - net-tools
    state: present

- name: install hwraid keys.
  tags:
    - base
  when: base_disk_monitoring
  apt_key:
    url: "https://hwraid.le-vert.net/debian/hwraid.le-vert.net.gpg.key"
    state: present

- name: add hwraid.le-vert.net apt repository
  tags:
    - hwraid
  when: base_disk_monitoring
  apt_repository:
    repo: "deb [arch=amd64] http://hwraid.le-vert.net/debian buster main"
    state: present

- name: update package lists
  tags:
    - base
  apt:
    update_cache: true

- name: install my configs
  tags:
    - base
  copy: src="configs/{{ item }}" dest="/home/chiefengineer/{{ item }}"
  with_items:
    - .tmux.conf

- name: install additional disk monitoring packages
  tags:
    - base
  when: base_disk_monitoring
  apt: 
    pkg:
      - zfsutils-linux
      - hddtemp
      - smartmontools
      - megacli
    state: present

- name: upgrade all packages
  tags:
    - base
  when: base_dist_upgrade
  apt:
    upgrade: dist
