# dhcpd config.
# default lease is 1 day
dhcp_global_default_lease_time: 43200
dhcp_global_max_lease_time: 604800
dhcp_global_bootp: deny

dhcp_global_authoritative: authoritative

dhcp_global_subnet_mask: 255.255.255.0
dhcp_global_broadcast_address: 192.168.9.255
dhcp_global_domain_name: klingon.alfors.org
dhcp_global_domain_name_servers:
  - 192.168.9.5
  - 192.168.9.7

dhcp_global_includes:
  - extra_opts.conf

dhcp_global_failover_peer: klingon-group
dhcp_global_failover:
  role: secondary
  address: 192.168.9.6
  port: 647
  peer_address: 192.168.9.5
  peer_port: 647
  max_response_delay: 30
  max_unacked_updates: 10
  load_balance_max_seconds: 5

dhcp_subnets:
  - ip: 192.168.9.0
    netmask: 255.255.255.0

    domain_search: klingon.alfors.org
    domain_name_servers:
      - 192.168.9.5
      - 192.168.9.7

    routers: 192.168.9.1

    pools:
      - name: one
        failover_peer: klingon-group
        range_begin: 192.168.9.100
        range_end: 192.168.9.220

# https://github.com/bertvv/ansible-role-dhcp/blob/vagrant-tests/test.yml
dhcp_hosts:
  - name: apmesh01
    mac: 'f0:9f:c2:a3:55:ff'
    ip: 192.168.9.4

  - name: frontdoor
    mac: 'ec:71:db:6b:0c:df'
    ip: 192.168.9.51

  - name: backyard
    mac: 'ec:71:db:ab:69:ff'
    ip: 192.168.9.52
  
  - name: catcam
    mac: 'ec:71:db:cb:8d:f0'
    ip: 192.168.9.53

# semi-perminant machines
  - name: prometheus
    mac: '04:d9:f5:1e:41:53'
    ip: 192.168.9.83

  - name: xbox360
    mac: 'b4:ae:2b:4e:af:af'
    ip: 192.168.9.88

  - name: quvat
    mac: '00:24:1d:d7:96:5b'
    ip: 192.168.9.75
  
  - name: colorlaser
    mac: 'b4:22:00:32:49:3b'
    ip: 192.168.9.71

