- name: knot-resolver pkg repos
  tags:
    - knot-resolver
  apt:
    deb: https://secure.nic.cz/files/knot-resolver/knot-resolver-release.deb

- name: install knot-resolver
  tags:
    - knot-resolver
  apt:
    pkg: [ 'knot-resolver' ] #, 'knot-resolver-module-http' ] # http doesn't currently work.
    state: present
    update_cache: true

- name: deploy config file
  tags:
    - knot-resolver
  template:
    src: kresd.conf.j2
    dest: "{{ kres_config_dir }}/kresd.conf"
  when: knot_resolver_use_j2_config 

- name: digicert exists
  tags:
    - knot-resolver
  stat:
    path: "{{ kres_config_dir }}/{{ kres_digicert }}"
  register: kres_digicert_res

- name: download cert
  when: not kres_digicert_res.stat.exists
  get_url:
    url: "{{ kres_digicert_url }}"
    dest: "{{ kres_config_dir }}/{{ kres_digicert }}"
#    checksum: "sha1:{{ unif_java_activation_sha1 }}"

#- name: enable knot-resolver
#  tags:
#    - knot-resolver
#  service:
#    name: kresd@1.service
#    enabled: true

- name: start knot-resolver
  tags:
    - knot-resolver
  shell: systemctl start kresd@1
