- name: knot-resolver pkg repos
  tags:
    - knot-resolver
  apt:
    deb: https://secure.nic.cz/files/knot-resolver/knot-resolver-release.deb

- name: install knot-resolver
  tags:
    - knot-resolver
  apt:
    pkg: knot-resolver
    state: present
    update_cache: true

- name: deploy config file
  tags:
    - knot-resolver
  template:
    src: kresd.conf.j2
    dest: /etc/knot-resolver/kresd.conf

#- name: enable knot-resolver
#  tags:
#    - knot-resolver
#  service:
#    name: kresd@1.service
#    enabled: true

- name: start knot-resolver
  tags:
    - knot-resolver
  shell: systemctl start kresd@1

