
# check for key at /usr/share/keyrings/knot-dns.cz/apt.key
# maybe check that the fingerprint matches?
# mk dir/pull key if necessary.


## remove old repo, install new repo.
- name: knot-dns pkg repos
  tags:
    - knot-dns
  apt_repository:
    repo: "deb https://deb.knot-dns.cz/knot-latest/ bullseye main"
    state: absent

- name: grab new key for knot-dns
  tags:
    - knot-dns
  get_url:
    url: "https://deb.knot-dns.cz/apt.gpg"
    dest: /usr/share/keyrings/knot-dns.cz-apt.gpg
    mode: '0644'
    force: false

- name: add new repo for knotdns
  tags:
    - knot-dns
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/knot-dns.cz-apt.gpg] https://deb.knot-dns.cz/knot-latest/ bullseye main"
    state: present

- name: install knot-dns
  tags:
    - knot-dns
  apt:
    pkg: [ 'knot', 'knot-dnsutils']
    state: present
    update_cache: true

- name: check config dir
  tags:
    - knot-dns
  stat:
    path: /etc/knot/zones
  register: knot_dns_zones_res

- name: make config dir.
  tags:
    - knot-dns
  when: not knot_dns_zones_res.stat.exists
  file:
    path: /etc/knot/zones/
    mode: 0755
    state: directory
  
- name: deploy config file
  tags:
    - knot-dns
  template:
    src: knot.conf.j2
    dest: /etc/knot/knot.conf
