---
# Version configuration.
docker_compose_version: "2.0.1"
docker_compose_map_arm64: "aarch64"

docker_compose_arch: "{{ lookup('vars', 'docker_compose_map_' + host_golang_arch, default='{{ host_golang_arch }}') }}"

# Static configuration.
docker_compose_path: "/usr/libexec/docker/cli-plugins/"
docker_compose_bin: "docker-compose-linux-{{ docker_compose_arch }}"
docker_compose_url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/{{ docker_compose_bin }}"
