---
# https://github.com/restic/restic/releases/download/v0.9.6/restic_0.9.6_linux_amd64.bz2
# Version configuration.
restic_version: "0.12.1"
# Static configuration.
restic_dir: "restic_{{ restic_version }}_linux_{{ host_golang_arch }}"
restic_url: "https://github.com/restic/restic/releases/download/v{{ restic_version }}/{{ restic_dir }}.bz2"
restic_bz2: "/tmp/restic.bz2"

