version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-aarch64
    shm_size: "64mb"
    devices:
      - /dev/apex_0
      # this is the coral ai tpu.
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sdcard/frigate/config:/config
      - /usbdrive/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 256000000
          # 256MB.
    ports:
      - 192.168.9.194:5000:5000
      - 1935:1935
    environment:
      FRIGATE_CAM_UN: ${CAM_UN}
      FRIGATE_CAM_PW: ${CAM_PW}
      FRIGATE_RTSP_UN: ${FRIGATE_RTSP_UN}
      FRIGATE_RTSP_PW: ${FRIGATE_RTSP_PW}
    depends_on:
      - mqtt

  mqtt:
    container_name: mqtt
    restart: unless-stopped
    image: eclipse-mosquitto:2.0
    volumes:
      - /sdcard/frigate/mqtt/data:/mosquitto/data
      - /sdcard/frigate/mqtt/log:/mosquitto/log
      - /sdcard/frigate/mqtt/config:/mosquitto/config
