version: "3.8"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: blakeblackshear/frigate:stable-aarch64
    shm_size: "64mb"
    devices:
      - /dev/apex_0
      # this is the coral ai tpu.
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # config
      - /sdcard/frigate/config:/config
      # everything else.
      # db (sqlite), snapshots, recordings
      - /usbdrive/frigate:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 256000000
          # 256MB.
    ports:
      - 5000:5000
      - 1935:1935
    environment:
      FRIGATE_CAM_UN: ${CAM_UN}
      FRIGATE_CAM_PW: ${CAM_PW}
    depends_on:
      - mqtt

  mqtt:
    container_name: mqtt
    restart: unless-stopped
    image: eclipse-mosquitto:2.0
    volumes:
      - /sdcard/frigate/mqtt/data:/mosquitto/data
      - /sdcard/frigate/mqtt/log:/mosquitto/log
      - /sdcard/frigate/mqtt/config:/mosquitto/config

  traefik:
    container_name: traefik
    restart: unless-stopped
    image: traefik:v2.5.3
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - CF_API_EMAIL=${CF_API_USER}
      - CF_DNS_API_TOKEN=${CF_API_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sdcard/frigate/traefik.yml:/etc/traefik/traefik.yml
      - /sdcard/frigate/traefik-sites/:/traefik
      - /sdcard/frigate/acme.json:/acme.json
    depends_on:
      - traefik-forward-auth
  
  traefik-forward-auth:
    container_name: traefik-forward-auth
    restart: unless-stopped
    image: thomseddon/traefik-forward-auth:2-arm64
    command: ["--whitelist=${MY_EMAIL}", "--whitelist=${OWNER_EMAIL}", "--whitelist=${WIFE_EMAIL}", "--whitelist=${HER_EMAIL}", "--whitelist=${AUX_EMAIL}"]
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=${GG_CLIENT_ID}
      - PROVIDERS_GOOGLE_CLIENT_SECRET=${GG_CLIENT_SECRET}
      - SECRET=${TFA_SECRET}
      - INSECURE_COOKIE=false
      - LOG_LEVEL=info
    labels:
      traefik.http.middlewares.traefik-forward-auth.forwardauth.address: http://traefik-forward-auth:4181
      traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders: X-Forwarded-User
      traefik.http.services.traefik-forward-auth.loadbalancer.servers.url: http://traefik-forward-auth:4181
