mqtt:
  host: mqtt

detectors:
  coralcpu:
    type: edgetpu
    device: ""
# per docs, use empty device for the dev board.

database:
  path: /config/frigate.db

ffmpeg:
  global_args: -hide_banner -loglevel error

  # copied from page for reolink 410/520
  input_args:
    - -avoid_negative_ts
    - make_zero
    - -fflags
    - nobuffer+genpts+discardcorrupt
    - -flags
    - low_delay
    - -strict
    - experimental
    - -analyzeduration
    - 1000M
    - -probesize
    - 1000M
    - -rw_timeout
    - "5000000"
  
  output_args:
    record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy

rtmp:
  enabled: False

objects:
  track:
    - person
    - dog
    - cat

detect:
  enabled: True
  max_disappeared: 25

record:
  enabled: True
  retain_days: 1
  events:
    max_seconds: 600
    pre_capture: 15
    post_capture: 15

    retain:
      default: 20

cameras:
  backdoor:
    ffmpeg:
      inputs:
        - path: http://192.168.9.200/flv?port1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_UN}&password={FRIGATE_CAM_PW}
          roles:
            - record
        - path: http://192.168.9.200/flv?port1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_UN}&password={FRIGATE_CAM_PW}
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    motion:
      mask:
        - 186,30,450,30,450,10,186,10
  cats:
    ffmpeg:
      inputs:
        - path: http://192.168.9.146/flv?port1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAM_UN}&password={FRIGATE_CAM_PW}
          roles:
            - record
        - path: http://192.168.9.146/flv?port1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAM_UN}&password={FRIGATE_CAM_PW}
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 7
    motion:
      mask:
        - 186,30,450,30,450,10,186,10
  frontdoor:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - "1"
      inputs:
        - path: rtsp://{FRIGATE_RTSP_UN}:{FRIGATE_RTSP_PW}@192.168.9.51:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://{FRIGATE_RTSP_UN}:{FRIGATE_RTSP_PW}@192.168.9.51:554/h264Preview_01_main
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 7
    motion:
      mask:
        - 410,444,410,470,221,470,221,444
  backyard:
    ffmpeg:
      input_args:
        - -avoid_negative_ts
        - make_zero
        - -fflags
        - nobuffer
        - -flags
        - low_delay
        - -strict
        - experimental
        - -fflags
        - +genpts+discardcorrupt
        - -use_wallclock_as_timestamps
        - "1"
      inputs:
        - path: rtsp://{FRIGATE_RTSP_UN}:{FRIGATE_RTSP_PW}@192.168.9.52:554/h264Preview_01_sub
          roles:
            - detect
        - path: rtsp://{FRIGATE_RTSP_UN}:{FRIGATE_RTSP_PW}@192.168.9.52:554/h264Preview_01_main
          roles:
            - record
    detect:
      width: 640
      height: 480
      fps: 7
    motion:
      mask:
        - 410,444,410,470,221,470,221,444

