http:
  middlewares:
    traefik-forward-auth:
      forwardauth:
        address: "http://traefik-forward-auth:4181"
        authResponseHeaders: "X-Forwarded-User"
 
  services:
    traefik-forward-auth:
      loadbalancer:
        servers:
          - url: http://traefik-forward-auth:4181
