---
- name: add docker apt key
  tags:
    - docker
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: add docker apt repository
  tags:
    - docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
    state: present

- name: update package lists
  tags:
    - docker
  apt:
    update_cache: true

- name: install docker
  tags:
    - docker
  apt:
    pkg: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: present

- name: start docker service
  tags:
    - docker
  service:
    name: docker.service
    state: started
    enabled: true
