---
atomicpi:
  hosts:
    #192.168.9.122:
    192.168.9.174:

  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "amd64"
    
    node_exporter_force: true
    node_exporter_sha256: "344bd4c0bbd66ff78f14486ec48b89c248139cdd485e992583ea30e89e0e5390"
    node_exporter_extra_options: ""
    
    docker_compose_sha256: "184df811a70366fa339e99df38fc6ff24fc9e51b3388335efe51c1941377d4ce"

    base_custom_packages_install: true
    base_custom_packages:
      - nfs-common
      - vainfo
      - intel-gpu-tools
      - btrfs-progs

