---
#- hosts: all
#  roles:
#    - base
#    - node_exporter

- hosts: apphost
  roles:
    - mqtt2prometheus
    - grafana
    - restic

#- hosts: wigwag
#    - homeassistant
#    - restic

- hosts: pegasus.klingon.alfors.org
  roles:
    - restic

