---
#- hosts: all
#  roles:
#    - base
#    - node_exporter

#- hosts: apphost
#  roles:
#    - mqtt2prometheus
#    - grafana
#    - restic

#- hosts: wigwag.klingon.alfors.org
#  roles:
#    - homeassistant
#    - restic
#    - wigwag

#- hosts: all
#  roles:
#    - restic

- hosts: arm64
  roles:
    - base
    - node_exporter
    - restic

- hosts: defiant.klingon.alfors.org
  roles:
#    - docker
#    - knot-resolver
#    - knot-dns
#    - bertvv.dhcp

- hosts: ganges.klingon.alfors.org
  roles:
#    - docker

- hosts: korana.klingon.alfors.org
  roles:
    - knot-resolver

  vars:
    unifi_java_home: /usr/lib/jvm/
  