---
amd64:
  hosts:
    bortas.klingon.alfors.org:
      host_internal_addr: "192.168.9.7"
      resticbk_repo_url: "rest:http://192.168.9.22:1801/foo"
      resticbk_timer_time: "01:01:00"
      resticbk_backup_list:
        - /etc/knot/
        - /etc/knot-resolver
        - /root
        - /home/        
      promtail_config_clients:
        - url: "http://192.168.9.21:3100/loki/api/v1/push"
    
    ## former hosts
    valiant.klingon.alfors.org:
    # app server
    #grissom.klingon.alfors.org:
    #  mqtt2prometheus_sha256: "5d9b9f75eb3eb24a9cc68cc2caa253e1e420e02f14d02b02a93f78b700270c9d"
  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "amd64"
    base_disk_monitoring: false
    base_dist_upgrade: false

    docker_compose_sha256: "36d1728ce001c7f021294be43bdfa3f508038bb00886c34b0794f7731cc9bf4b"
    node_exporter_sha256: "e77ff1b0a824a4e13f82a35d98595fe526849c09e3480d0789a56b72242d2abc"
    node_exporter_extra_options: "--no-collector.mdadm"
    restic_sha256: "c8da7350dc334cd5eaf13b2c9d6e689d51e7377ba1784cc6d65977bd44ee1165"
    promtail_config_clients:
      - url: "https://loki.klingon.alfors.org/loki/api/v1/push"

arm64:
  hosts:
    # dns/caching dns and dhcpd server.
    defiant.klingon.alfors.org:
      host_internal_addr: "192.168.9.5"
      base_strongswan: true
      resticbk_repo_url: "rest:http://192.168.9.22:1801/foo"
      resticbk_timer_time: "00:01:00"
      resticbk_backup_list:
        - /etc/knot/
        - /etc/knot-resolver
        - /root
        - /home/
      
      promtail_config_clients:
        - url: "https://192.168.9.21:3100/loki/api/v1/push"
      

    # backup caching dns (some day backup/failover dhcpd) and strongswan (ipsec) server
    korana.klingon.alfors.org:
      host_internal_addr: "192.168.9.6"
      resticbk_repo_url: "rest:http://192.168.9.22:1801/foo"
      resticbk_timer_time: "00:20:00"
      resticbk_backup_list:
        - /root
        - /home
        - /srv/docker
        - /etc/knot-resolver
        - /etc/knot
      
      promtail_config_clients:
        - url: "http://192.168.9.21:3100/loki/api/v1/push"
      portainer_agent_volumepath: /ssd/docker/volumes

    # video.
    ganges.klingon.alfors.org:
      host_internal_addr: "192.168.9.42"
    
    orinoco.klingon.alfors.org:
      host_internal_addr: "192.168.9.43"
      base_cpupower: false
      resticbk_timer_time: "00:40:00"

  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "arm64"
    base_cpupower: true
    base_disk_monitoring: false
    base_dist_upgrade: false
    node_exporter_sha256: "0b20aa75385a42857a67ee5f6c7f67b229039a22a49c5c61c33f071356415b59"
    node_exporter_extra_options: ""
    docker_compose_sha256: "a2c9819115df18ada4e6a68be37f6515121984189d379456bdfd53058e07128b"
    restic_sha256: "24c7ca3fe6905b3a493a67237ff081ba9e11abfb27dcb73f18d0a4595926c35d"
    promtail_config_clients:
      - url: "https://loki.klingon.alfors.org/loki/api/v1/push"

    
mipsle:
  hosts:
    gateway.klingon.alfors.org:
      host_internal_addr: "192.168.9.1"
  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "mipsle"
    base_cpupower: false
    base_disk_monitoring: false
    base_dist_upgrade: false
    node_exporter_use_textfile: false
    node_exporter_extra_options: "--log.level=warn --web.max-requests=5 --collector.disable-defaults --colllector.arp --collector.conntrack --collector.cpu --collector.diskstats --collector.entropy --collector.filefd --collector.filesystem --collector.loadavg --collector.meminfo --collector.netclass --collector.netdev --collector.netdev.device-blacklist=lo --collector.pressure --collector.sockstat --collector.softnet --collector.stat --collector.time --collector.timex --collector.udp_queues --collector.uname"
    node_exporter_sha256: "ed11d97af2482130a4b6c6b24190a21b74f13762b01fc8e63e164c7e2ce73653"

servers:
    hosts:
#      valiant.klingon.alfors.org:
#      grissom.klingon.alfors.org:
      defiant.klingon.alfors.org:
      korana.klingon.alfors.org:
      ganges.klingon.alfors.org:
      orinoco.klingon.alfors.org:

dhcp:
  hosts:
    #korana.klingon.alfors.org:
    defiant.klingon.alfors.org:
    bortas.klingon.alfors.org:

pa:
  hosts:
    bortas.klingon.alfors.org:
    korana.klingon.alfors.org:
    defiant.klingon.alfors.org:
    ganges.klingon.alfors.org:
    orinoco.klingon.alfors.org:

dockers:
  hosts:
    bortas.klingon.alfors.org:
    defiant.klingon.alfors.org:
    korana.klingon.alfors.org:
    ganges.klingon.alfors.org:
    orinoco.klingon.alfors.org:
