---
amd64:
  hosts:
    gateway.klingon.alfors.org:
      node_exporter_use_textfile: false
      node_exporter_extra_options: "--no-collector.mdadm --no-collector.schedstat"
    pegasus.klingon.alfors.org:
      node_exporter_use_textfile: true
      node_exporter_extra_options: "--no-collector.mdadm"
      restic_sha256: "a88ca09d1dd051d470965667a224a2b81930c6628a0566b7b17868be40207dc8"
  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "amd64"
    base_disk_monitoring: false
    base_dist_upgrade: false
    node_exporter_sha256: "f175cffc4b96114e336288c9ea54b54abe793ae6fcbec771c81733ebc2d7be7c"

arm7:
  hosts:
    wigwag.klingon.alfors.org:
  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "armv7"
    base_disk_monitoring: false
    base_dist_upgrade: false
    node_exporter_use_textfile: false
    node_exporter_extra_options: "--no-collector.mdadm --no-collector.schedstat"
    node_exporter_sha256: "93fb701bad18c2a0347abad17a3b946a5ed4bd27bcb13792ea079618b874a83c"

server:
  hosts:
    pegasus.klingon.alfors.org:
    gateway.klingon.alfors.org:
    wigwag.klingon.alfors.org:
