---
amd64:
  hosts:
    valiant.klingon.alfors.org:
    # app server
    grissom.klingon.alfors.org:
      mqtt2prometheus_sha256: "5d9b9f75eb3eb24a9cc68cc2caa253e1e420e02f14d02b02a93f78b700270c9d"
  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "amd64"
    base_disk_monitoring: false
    base_dist_upgrade: false
    node_exporter_sha256: "344bd4c0bbd66ff78f14486ec48b89c248139cdd485e992583ea30e89e0e5390"
    node_exporter_extra_options: "--no-collector.mdadm"
    restic_sha256: "11d6ee35ec73058dae73d31d9cd17fe79661090abeb034ec6e13e3c69a4e7088"
    promtail_config_clients:
      - url: "https://loki.klingon.alfors.org/loki/api/v1/push"

arm64:
  hosts:
    # dns/caching dns and dhcpd server.
    defiant.klingon.alfors.org:
      host_internal_addr: "192.168.9.5"
      base_strongswan: true
      resticbk_repo_url: "rest:http://192.168.9.22:1801/foo"
      resticbk_backup_list:
        - /etc/knot/
        - /etc/knot-resolver
        - /root
        - /home/
      
      promtail_config_clients:
        - url: "https://192.168.9.21:3100/loki/api/v1/push"
      

    # backup caching dns (some day backup/failover dhcpd) and strongswan (ipsec) server
    korana.klingon.alfors.org:
      host_internal_addr: "192.168.9.6"
      resticbk_repo_url: "rest:http://192.168.9.22:1801/foo"
      resticbk_backup_list:
        - /root
        - /home
        - /srv/docker
        - /etc/knot-resolver
        - /etc/knot
      
      promtail_config_clients:
        - url: "http://192.168.9.21:3100/loki/api/v1/push"
      portainer_agent_volumepath: /ssd/docker/volumes

    # video.
    ganges.klingon.alfors.org:
      host_internal_addr: "192.168.9.42"
    
    orinoco.klingon.alfors.org:
      host_internal_addr: "192.168.9.43"
      base_cpupower: false

  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "arm64"
    base_cpupower: true
    base_disk_monitoring: false
    base_dist_upgrade: false
    node_exporter_sha256: "b78464d8bd1b770a7f818d20c78410090f64a91b13577f1883dca1eec5aedbc9"
    node_exporter_extra_options: ""
    docker_compose_sha256: "002662ed18a22d9d65d3d2c0358008c7c6a3db7dacb8983488130b3954d00e63"
    restic_sha256: "c7e58365d0b888a60df772e7857ce8a0b53912bbd287582e865e3c5e17db723f"
    promtail_config_clients:
      - url: "https://loki.klingon.alfors.org/loki/api/v1/push"

    
mipsle:
  hosts:
    gateway.klingon.alfors.org:
      host_internal_addr: "192.168.9.1"
  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "mipsle"
    base_cpupower: false
    base_disk_monitoring: false
    base_dist_upgrade: false
    node_exporter_use_textfile: false
    node_exporter_extra_options: "--log.level=warn --web.max-requests=5 --collector.disable-defaults --colllector.arp --collector.conntrack --collector.cpu --collector.diskstats --collector.entropy --collector.filefd --collector.filesystem --collector.loadavg --collector.meminfo --collector.netclass --collector.netdev --collector.netdev.device-blacklist=lo --collector.pressure --collector.sockstat --collector.softnet --collector.stat --collector.time --collector.timex --collector.udp_queues --collector.uname"
    node_exporter_sha256: "ed11d97af2482130a4b6c6b24190a21b74f13762b01fc8e63e164c7e2ce73653"

servers:
    hosts:
#      valiant.klingon.alfors.org:
#      grissom.klingon.alfors.org:
      defiant.klingon.alfors.org:
      korana.klingon.alfors.org:
      ganges.klingon.alfors.org:
      orinoco.klingon.alfors.org:

dhcp:
  hosts:
    korana.klingon.alfors.org:
    defiant.klingon.alfors.org:

pa:
  hosts:
    korana.klingon.alfors.org:
    defiant.klingon.alfors.org:
    ganges.klingon.alfors.org:
    orinoco.klingon.alfors.org:

dockers:
  hosts:
    defiant.klingon.alfors.org:
    korana.klingon.alfors.org:
    ganges.klingon.alfors.org:
    orinoco.klingon.alfors.org:
