---
amd64:
  hosts:
    pegasus.klingon.alfors.org:
      node_exporter_use_smartmon: true
      node_exporter_extra_options: "--no-collector.mdadm"
      mqtt2prometheus_sha256: "5d9b9f75eb3eb24a9cc68cc2caa253e1e420e02f14d02b02a93f78b700270c9d"
      docker_compose_sha256: "90990e7268e954e7930353650d7bcf5a37d29c77925ea2066335367b5f27ec9a"
      resticbk_backup_list:
        - /root/
        - /home
        - /r1/docker/
        - /srv/docker/
        - /app
        - /etc/postfix
        - /etc/docker/daemon.json
        - /etc/cron.d/
        - /boot
        - /etc/exports
        - /etc/network/interfaces
        - /etc/crypttab
        - /etc/keys/

      resticbk_exclude_list:
        - /r1/docker/plex
        - /r1/docker/photoprism/originals
        - /srv/docker/plex


    unifi.klingon.alfors.org:
#    gateway.klingon.alfors.org:
#      node_exporter_use_textfile: false
#      node_exporter_extra_options: "--no-collector.mdadm --no-collector.schedstat"
#      restic_repo_url: "rest:http://192.168.9.22:1801/foo"
#      host_internal_addr: "192.168.9.1"
  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "amd64"
    base_disk_monitoring: false
    base_dist_upgrade: false
    node_exporter_sha256: "344bd4c0bbd66ff78f14486ec48b89c248139cdd485e992583ea30e89e0e5390"
    restic_sha256: "11d6ee35ec73058dae73d31d9cd17fe79661090abeb034ec6e13e3c69a4e7088"

servers:
  hosts:
    pegasus.klingon.alfors.org:
    unifi.klingon.alfors.org:
#    gateway.klingon.alfors.org:

pa:
  hosts:

dockers:
  hosts:
    pegasus.klingon.alfors.org: