---
amd64:
  hosts:
    valiant.klingon:
    grissom.klingon:
      mqtt2prometheus_sha256: "4d5fd74c51bb1facd8a444f8c9e70a07543c0d2b61d4bc285821b5d61076930b"
  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "amd64"
    base_disk_monitoring: false
    base_dist_upgrade: false
    node_exporter_sha256: "f175cffc4b96114e336288c9ea54b54abe793ae6fcbec771c81733ebc2d7be7c"
    node_exporter_use_textfile: false
    node_exporter_extra_options: "--no-collector.mdadm"

server:
    hosts:
      valiant.klingon:
      grissom.klingon:
  
apphost:
  hosts:
    grissom.klingon: