---
amd64:
  hosts:
    gateway.klingon.alfors.org:
      node_exporter_use_textfile: false
      node_exporter_extra_options: "--no-collector.mdadm --no-collector.schedstat"
      restic_repo_url: "rest:http://192.168.9.22:8000/foo"
      host_internal_addr: "192.168.9.1"
    pegasus.klingon.alfors.org:
      node_exporter_use_textfile: true
      node_exporter_extra_options: "--no-collector.mdadm"
  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "amd64"
    base_disk_monitoring: false
    base_dist_upgrade: false
    node_exporter_sha256: "3369b76cd2b0ba678b6d618deab320e565c3d93ccb5c2a0d5db51a53857768ae"
    restic_sha256: "41d47f100f61c503c462f53069e5c2aaad4dafec461e56b85b1de7730e4f9c4d"

arm7:
  hosts:
    wigwag.klingon.alfors.org:
  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "arm"
    base_disk_monitoring: false
    base_dist_upgrade: false
    restic_sha256: "9ffa244293433033702bbbbddf85e116221a7ff75c0b2bd152d9da8b6263ea6f"
    node_exporter_use_textfile: false
    node_exporter_extra_options: "--no-collector.mdadm --no-collector.schedstat"
    node_exporter_sha256: "93fb701bad18c2a0347abad17a3b946a5ed4bd27bcb13792ea079618b874a83c"

server:
  hosts:
    pegasus.klingon.alfors.org:
    gateway.klingon.alfors.org:
    wigwag.klingon.alfors.org:
