---
amd64:
  hosts:
    172.24.78.73:
    valiant.klingon.alfors.org:
    # app server
    grissom.klingon.alfors.org:
      mqtt2prometheus_sha256: "5d9b9f75eb3eb24a9cc68cc2caa253e1e420e02f14d02b02a93f78b700270c9d"
  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "amd64"
    base_disk_monitoring: false
    base_dist_upgrade: false
    node_exporter_sha256: "3369b76cd2b0ba678b6d618deab320e565c3d93ccb5c2a0d5db51a53857768ae"
    node_exporter_use_textfile: false
    node_exporter_extra_options: "--no-collector.mdadm"
    restic_sha256: "f559e774c91f1201ffddba74d5758dec8342ad2b50a3bcd735ccb0c88839045c"
    promtail_config_clients:
      - url: "https://loki.klingon.alfors.org/loki/api/v1/push"

arm64:
  hosts:
    # dns/caching dns and dhcpd server.
    defiant.klingon.alfors.org:
      host_internal_addr: "192.168.9.5"
      base_strongswan: true
      restic_repo_url: "rest:http://192.168.9.22:1801/foo"
      promtail_config_clients:
        - url: "https://192.168.9.21:3100/loki/api/v1/push"
    # backup caching dns (some day backup/failover dhcpd) and strongswan (ipsec) server
    korana.klingon.alfors.org:
      host_internal_addr: "192.168.9.6"
      restic_repo_url: "rest:http://192.168.9.22:1801/foo"
      promtail_config_clients:
        - url: "http://192.168.9.21:3100/loki/api/v1/push"

    # video.
    ganges.klingon.alfors.org:
      host_internal_addr: "192.168.9.42"
    
    orinoco.klingon.alfors.org:
      host_internal_addr: "192.168.9.43"
      base_cpupower: false

  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "arm64"
    base_cpupower: true
    base_disk_monitoring: false
    base_dist_upgrade: false
    node_exporter_sha256: "017514906922fcc4b7d727655690787faed0562bc7a17aa9f72b0651cb1b47fb"
    node_exporter_use_textfile: false
    node_exporter_extra_options: ""
    restic_sha256: "22cc11da0c91690bdea21d873ea341d8d31f44ba32602a2e3c40809b334cdf19"
    promtail_config_clients:
      - url: "https://loki.klingon.alfors.org/loki/api/v1/push"

    
mipsle:
  hosts:
    gateway.klingon.alfors.org:
      host_internal_addr: "192.168.9.1"
  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "mipsle"
    base_cpupower: false
    base_disk_monitoring: false
    base_dist_upgrade: false
    node_exporter_use_textfile: false
    node_exporter_extra_options: "--log.level=warn --web.max-requests=5 --collector.disable-defaults --colllector.arp --collector.conntrack --collector.cpu --collector.diskstats --collector.entropy --collector.filefd --collector.filesystem --collector.loadavg --collector.meminfo --collector.netclass --collector.netdev --collector.netdev.device-blacklist=lo --collector.pressure --collector.sockstat --collector.softnet --collector.stat --collector.time --collector.timex --collector.udp_queues --collector.uname"
    node_exporter_sha256: "85f0a24c07c5d8237caf36a5c68a63958280dab802b5056ff36d75563d5e5241"

servers:
    hosts:
      valiant.klingon.alfors.org:
      grissom.klingon.alfors.org:
      defiant.klingon.alfors.org:
      korana.klingon.alfors.org:
      ganges.klingon.alfors.org:
#      172.24.78.73:
  
apphost:
  hosts:
    grissom.klingon.alfors.org:
