---
amd64:
  hosts:
    pegasus.klingon.alfors.org:
      node_exporter_use_smartmon: true
      node_exporter_extra_options: "--no-collector.mdadm"
      mqtt2prometheus_sha256: "5d9b9f75eb3eb24a9cc68cc2caa253e1e420e02f14d02b02a93f78b700270c9d"
      resticbk_timer_timer: "01:40:00"
      resticbk_backup_list:
        - /root/
        - /home
        - /r1/docker/
        - /srv/docker/
        - /app
        - /etc/postfix
        - /etc/docker/daemon.json
        - /etc/cron.d/
        - /boot
        - /etc/exports
        - /etc/network/interfaces
        - /etc/crypttab
        - /etc/keys/

      resticbk_exclude_list:
        - /r1/docker/plex
        - /r1/docker/photoprism/originals
        - /srv/docker/plex


    unifi.klingon.alfors.org:
#    gateway.klingon.alfors.org:
#      node_exporter_use_textfile: false
#      node_exporter_extra_options: "--no-collector.mdadm --no-collector.schedstat"
#      restic_repo_url: "rest:http://192.168.9.22:1801/foo"
#      host_internal_addr: "192.168.9.1"
  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "amd64"
    base_disk_monitoring: false
    base_dist_upgrade: false
    docker_compose_sha256: "0b20aa75385a42857a67ee5f6c7f67b229039a22a49c5c61c33f071356415b59"
    node_exporter_sha256: "e77ff1b0a824a4e13f82a35d98595fe526849c09e3480d0789a56b72242d2abc"
    restic_sha256: "c8da7350dc334cd5eaf13b2c9d6e689d51e7377ba1784cc6d65977bd44ee1165"

servers:
  hosts:
    pegasus.klingon.alfors.org:
    unifi.klingon.alfors.org:
#    gateway.klingon.alfors.org:

pa:
  hosts:

dockers:
  hosts:
    pegasus.klingon.alfors.org: