---
amd64:
  hosts:
    pegasus.klingon.alfors.org:
      node_exporter_use_smartmon: true
      node_exporter_extra_options: "--no-collector.mdadm"
      mqtt2prometheus_sha256: "5d9b9f75eb3eb24a9cc68cc2caa253e1e420e02f14d02b02a93f78b700270c9d"
      resticbk_backup_list:
        - /root/
        - /home
        - /r1/docker/
        - /srv/docker/
        - /app
        - /etc/postfix
        - /etc/docker/daemon.json
        - /etc/cron.d/
        - /boot
        - /etc/exports
        - /etc/network/interfaces
        - /etc/crypttab
        - /etc/keys/

      resticbk_exclude_list:
        - /r1/docker/plex
        - /r1/docker/photoprism/originals
        - /srv/docker/plex


    unifi.klingon.alfors.org:
#    gateway.klingon.alfors.org:
#      node_exporter_use_textfile: false
#      node_exporter_extra_options: "--no-collector.mdadm --no-collector.schedstat"
#      restic_repo_url: "rest:http://192.168.9.22:1801/foo"
#      host_internal_addr: "192.168.9.1"
  vars:
    host_bin_path: "/usr/sbin"
    host_golang_arch: "amd64"
    base_disk_monitoring: false
    base_dist_upgrade: false
    docker_compose_sha256: "184df811a70366fa339e99df38fc6ff24fc9e51b3388335efe51c1941377d4ce"
    node_exporter_sha256: "68f3802c2dd3980667e4ba65ea2e1fb03f4a4ba026cca375f15a0390ff850949"
    restic_sha256: "a7a82eca050224c9cd070fea1d4208fe92358c5942321d6e01eff84a77839fb8"

servers:
  hosts:
    pegasus.klingon.alfors.org:
    unifi.klingon.alfors.org:
#    gateway.klingon.alfors.org:

pa:
  hosts:

dockers:
  hosts:
    pegasus.klingon.alfors.org: