---
- hosts: bortas.klingon.alfors.org
  roles:
  - role: patrickjahns.promtail
    vars:
      promtail_log_level: "warn"

      promtail_config_server:
        disable: true
#      promtail_config_clients:
#        - url: "https://loki.klingon.alfors.org/loki/api/v1/push"
      promtail_config_scrape_configs:
        - job_name: journal
          journal:
            max_age: 12h
            labels:
              job: systemd-journal
          relabel_configs:
            - source_labels: ['__journal__systemd_unit']
              target_label: 'unit'
            - source_labels: ['__journal__hostname']
              target_label: 'host'
            - source_labels: ['__journal_priority_keyword']
              target_label: 'severity'
